### ISSUE TITLE
The result is strange in win10

### ISSUE THREAD

**Issue by 07hyx06** [mattpoggi/depthstillation#3]
Hi! Thanks for your great work.

I try to run the code in win10, and use `gcc -shared -o libwarping.dll warping.c` instead of `compile.sh`. I modified `lib = cdll.LoadLibrary("external/forward_warping/libwarping.so")` to `lib = cdll.LoadLibrary("external/forward_warping/libwarping.dll")`. Then I run `depthstillation.py` but obtain strange result like that (dCOCO/im1):
![95022_00](https://user-images.githubusercontent.com/52267384/119078975-d67eed00-ba29-11eb-85bb-5368543683bf.jpg)
 which is quite different from the result in supply. material. Did I miss something?

**Comment by mattpoggi** [comment]
Hi, 
wow, that's interesting :sweat_smile: I guess there is something occurring at low level... probably when passing NumPy data to the C wrapper? Not sure when, but I will try to reproduce this issue on Windows. 
For now, I would suggest running it in a Linux environment.

**Comment by 07hyx06** [comment]
Got it. I run the code in wsl2.0 and find it works well.
