### ISSUE TITLE
Optic flow generation on custom dataset

### ISSUE THREAD

**Issue by zhilaAI** [mattpoggi/depthstillation#4]
Hello, 
Thank you for your great idea and code. 
How can we apply your code to a custom dataset? I have video frames and want to generate the optic flow for my dataset. How can I use your code? Thank you.

**Comment by mattpoggi** [comment]
Hi @zhilaAI,
to run our pipeline, you need to first predict depth maps for every single frame (you can use https://github.com/intel-isl/MiDaS as we do). Then, you can use our code as shown with the sample image provided in this repo.

**Comment by zhilaAI** [comment]
> Hi @zhilaAI,
> to run our pipeline, you need to first predict depth maps for every single frame (you can use https://github.com/intel-isl/MiDaS as we do). Then, you can use our code as shown with the sample image provided in this repo.

Thank you.
