### ISSUE TITLE
Typo in the comment

### ISSUE THREAD

**Issue by 07hyx06** [mattpoggi/depthstillation#5]
https://github.com/mattpoggi/depthstillation/blob/a2fafcc8d78d55e77f831777c78f82e105a5f3f1/depthstillation.py#L186

I think it should be ```Random angles in -pi/18,pi/18, excluding -pi/36,pi/36 to avoid zeros / very small rotations```.

**Comment by mattpoggi** [comment]
Right, good catch :)
