### ISSUE TITLE
Png format to .flo format

### ISSUE THREAD

**Issue by zhilaAI** [mattpoggi/depthstillation#6]
Hello, 
Thank you for your great code. 
How did you train the models for optical flow where the ground truth should be in .flow but your code generates .png format?

Thank you.

**Comment by FilippoAleotti** [comment]
Hi,
You can both:
1) save depthstilled flow maps as flo file, instead of png
2) change the way you load the ground truths in your data loaders, as in [RAFT](https://github.com/princeton-vl/RAFT/blob/224320502d66c356d88e6c712f38129e60661e80/core/utils/frame_utils.py#L102 )

**Comment by zhilaAI** [comment]
Thanks for your response. 
For the first option, I tried but OpenCV and Matplotlib do not support the .flo format. 
I do try the second option.

**Comment by mattpoggi** [comment]
Hi,
to read .flo files you can use the `readFlow` function defined here:

https://github.com/princeton-vl/RAFT/blob/master/core/utils/frame_utils.py

**Comment by zhilaAI** [comment]
Hi, 
Ya, I checked the code and saw the readFlow function but the problem is writing files in .flo format. 
Thanks for your suggestion.

**Comment by mattpoggi** [comment]
Sorry, my misunderstanding. From the same file, have you tried the `writeFlow` function?

**Comment by zhilaAI** [comment]
No no thanks for your help. 
Yes, I tried to use writeFlow to convert png to .flo format but failed.

**Comment by mattpoggi** [comment]
Did you try it to save `flow_01` or `flow_16bit`?

**Comment by zhilaAI** [comment]
I tried flow_16bit

**Comment by mattpoggi** [comment]
Ok, that one is already converted to the KITTI format. You should try with `flow_01`

**Comment by zhilaAI** [comment]
I'll try the flow_01 file. 

Thank you.
