### ISSUE TITLE
Object motion in the generated dataset.

### ISSUE THREAD

**Issue by Sharpiless** [mattpoggi/depthstillation#9]
Thanks for your great work! But I have a small question about the moving object in the paper. Table 1 shows that adding moving objects gives better performance. However, in Table 2 and the following tables, the dCOCO does not appear to contain moving objects (with EPE=3.81 on KITTI 15). Do you implement the following experiments, including dDAVIS and dKITTI, without moving objects? This is very important to us because our recent work uses depthstillation as an important reference. We would appreciate receiving your reply.

**Comment by mattpoggi** [comment]
Hi, 
sorry for being late. The experiments after Tab. 2 are WITHOUT moving objects, as stated at the bottom of page 6, left column: "Thus, since our primary focus is on real environments, we choose (C) as the configuration for the following experiments."

**Comment by Sharpiless** [comment]
Thanks!
